Use a venv with halcyon
att-comdev/halcyon-kubernetes pull request #46
Opened 2017-02-07 20:54 UTC by retr0h

The instructions require a minimum version of Ansible.  Enforce these
dependencies through a venv.  Particularly useful when switching between
halcyon and other projects.  Also, useful for the future as Halcyon expands,
and may require additional pypi dependencies.

2017-02-07 21:57 UTC, v1k0d3n commented
@retr0h very nice addition, and very welcome! thank you for checking out, using and  submitting to the project. LGTM

2017-02-07 21:58 UTC, v1k0d3n approved these changes

2017-02-07 21:58 UTC, v1k0d3n commented on Makefile
> +.PHONY:clean venv
i was thinking about doing this at one point, and then got distracted on other projects. very clean change.

2017-02-07 22:15 UTC, aric49 commented
Testing your changes locally, i am getting the following errors when I run make.. Looks like the virtualenv might require setuptools to run?

```
aric@host:~/tmp/halcyon-kubernetes$ make
if [ ! -d venv ]; then \
    virtualenv --no-setuptools venv; \
fi
New python executable in /home/aric/tmp/halcyon-kubernetes/venv/bin/python
Installing pip, wheel...done.
. venv/bin/activate; pip install -r requirements.txt
Collecting ansible==2.2.1 (from -r requirements.txt (line 1))
  Using cached ansible-2.2.1.0.tar.gz
Could not import setuptools which is required to install from a source distribution.
Please install setuptools.
Makefile:4: recipe for target 'venv/bin/activate' failed
make: *** [venv/bin/activate] Error 1
```

I have the following versions of setuptools and virtualenv on my laptop in my parent Ansible installation:

```
virtualenv (15.1.0)
setuptools (26.1.1)
```

2017-02-08 02:59 UTC, v1k0d3n commented
@aric49 where are we on the jenkins pipeline for Halcyon? i think the team is ready to add this back, correct?

2017-02-08 05:20 UTC, retr0h commented
> Testing your changes locally, i am getting the following errors when I run make.. Looks like the virtualenv might require setuptools to run?

This looks more like a problematic python/pip/venv environment than a problem with this patchset.

2017-02-08 14:23 UTC, aric49 commented
~~@retr0h -- I wouldn't be surprised if this was an issue on my end... I've had a lot of issues with Python/Pip dependencies on my workstation.   @v1k0d3n Can you validate this works for you, and if so, then we can merge.~~

I retract my last comment. I got the venv configuration running by uninstalling and re-installing the virtualenv pip package:

`pip uninstall virtualenv; pip install virtualenv`

LGTM.   Good to merge.

2017-02-08 15:47 UTC, v1k0d3n requested changes

2017-02-08 15:47 UTC, v1k0d3n commented on README.md
> +3. From the root of the project:
this makes the assumptions that some pre-requisites are installed prior to make and venv activation. can you outline in the docs what packages need to be installed for users of the project?

2017-02-08 17:30 UTC, retr0h commented on README.md
> +3. From the root of the project:
Updated.

2017-02-08 19:31 UTC, v1k0d3n commented
thanks for the update. LGTM.

2017-02-08 19:31 UTC, merged